services:  
  auth-db:

  auth-server:
    build:
      context: ./auth
  
  db:

  backend:
    build:
      context: ./backend

  seed:
    build:
      context: ./seed
      dockerfile: Dockerfile

