services:  
  auth-db:
    image: mongo:8.0.20
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - "${AUTH_DB_PORT}:27017"
    volumes:
      - ./.volumes/mongodb:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  auth-server:
    image: ghcr.io/mariamair/shorelinebuildings/auth-server:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AUTH_DB_URI: ${AUTH_DB_URI}
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
      AUTH_LOG_LEVEL: ${AUTH_LOG_LEVEL}
      ACCESS_TOKEN_LIFE: ${ACCESS_TOKEN_LIFE}
      REFRESH_TOKEN_LIFE: ${REFRESH_TOKEN_LIFE}
      ACCESS_TOKEN_PRIVATE_KEY: ${ACCESS_TOKEN_PRIVATE_KEY}
      ACCESS_TOKEN_PUBLIC_KEY: ${ACCESS_TOKEN_PUBLIC_KEY}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"
    depends_on:
      auth-db:
        condition: service_healthy

  db:
    image: postgres:18.2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/
      - ./db/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./db/02-init-db.sh:/docker-entrypoint-initdb.d/02-init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    image: ghcr.io/mariamair/shorelinebuildings/backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ACCESS_TOKEN_PUBLIC_KEY: ${ACCESS_TOKEN_PUBLIC_KEY}
      DB_USER: ${DB_USER}
      DB_USER_PASSWORD: ${DB_USER_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      db:
        condition: service_healthy

  seed:
    image: ghcr.io/mariamair/shorelinebuildings/seed:${IMAGE_TAG:-latest}
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_USER_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      CSV_PATH: ${CSV_PATH}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seed/data:/app/seed/data

volumes:
  pg_data:
